### PR TITLE
Fixes #80 Improved UI of services page

### LINKED ISSUE #80: Improve UI of Services Page
image
This can be made more fun.

### PR DESCRIPTION
**Pull request by rajfauzdar**
Fixes #80 
I have added automatic slider which displays the services . It is fully responsive and number of cards shown varies on screen size.

image
Screenshot (810)
image

### CODE REVIEW

**Comment by rajfauzdar** [comment]
Please review the PR asap so that we can finalize this UI and improve the user experience overall.

**Comment by yazdanhaider** [comment]
Heyyy @rajfauzdar I've checked the implemented feature and UI responsiveness. And the automatic UI slider is not working, Please take a look at it.

**Comment by rajfauzdar** [comment]
This is the image of testimonials page and I have not made any change to that. I have only updated the Services page. Please share the image so that I can work on that

**Comment by rajfauzdar** [comment]
I'm working on it

**Comment by rajfauzdar** [comment]
@yazdanhaider I have fixed the UI and tested in diff screen sizes. 

https://github.com/user-attachments/assets/fb5a32de-c5d1-4d64-be59-d8399eda4224

**Comment by yazdanhaider** [comment]
Nice work @rajfauzdar ,The bug has been fixed but please update the carousel style of the image slider.

Style for reference
Screenshot 2024-10-22 at 2 13 36 AM

**Comment by rajfauzdar** [comment]
Hey I will start another issue and update the carousel style. This updation will take some time but I will do it as quickly as possible. Please merge this PR for now .

**Comment by yazdanhaider** [comment]
I understand @rajfauzdar, Please go ahead and update the carousel style just a few small changes are needed. Keep up the good work and best of luck with completing your Hacktoberfest goal!

**Pull request closed without merging**
