### PR TITLE
Ui of the patient section is been updated

### PR DESCRIPTION
**Pull request by rohitja26**
Ui of the patient section is been updated

### CODE REVIEW

**Comment by rohitja26** [comment]
@yazdanhaider  please check and merge to the main ASAP please

**Comment by yazdanhaider** [comment]
fix the bug!! unable to add the patient. 


https://github.com/user-attachments/assets/915ff0f0-9ecf-45af-8578-c83c953efac1

**Comment by rohitja26** [comment]
Done in my latest commit @yazdanhaider please check now



https://github.com/user-attachments/assets/3520f0f1-4be0-4138-a583-cea5f69db006

**Comment by yazdanhaider** [comment]
Great!! thanks for contributing @rohitja26

**Comment by rohitja26** [comment]
thanks you @yazdanhaider  but the thinks has not done yet we make this project at a large level if you support

**Pull request merged**
