### PR TITLE
Updated the doctors page UI by adding pop up for displaying the doctor's profile details instead of showing the details in separate page

### PR DESCRIPTION
**Pull request by Jhananithaa**
**Changes made:**
1. Implemented a pop-up modal that displays detailed information about the doctor when a user clicks on a doctor profile card. The modal includes:
- Doctor's experience, qualifications, and bio.
- A "Book Appointment" button that redirects users to the appointment booking page.
2. Removed the "View Profile" button from the doctor profile cards to streamline the interface and focus on the new pop-up functionality.

**Before changes:**
image

**After changes:**
image
image

### CODE REVIEW

**Comment by Jhananithaa** [comment]
Hi @yazdanhaider, I have made a PR Please kindly review it.
Thankyou!

**Comment by Jhananithaa** [comment]
@yazdanhaider - Thankyou for review. Sure I will add. Just confirming, I will make it ina way that when the user click on the 'i' button, then the pop up will come. Will that fine!

**Comment by Jhananithaa** [comment]
@yazdanhaider - I have made the changes. could you please kindly check.
i button added
image
when the user clicks on it, pop up will come
image

**Comment by Jhananithaa** [comment]
@yazdanhaider - I have made changes. Please kindly review
1. Reduced the i icon. 
2. Enabled on click option so that when the user click on the card the pop will come and this is same for i icon also
image

**Comment by yazdanhaider** [comment]
Looks good, but please adjust the "i" button to the right corner. Also add a close functionality when clicking outside the card. The popup should close when users click outside the box.

**Comment by Jhananithaa** [comment]
Sure @yazdanhaider so the i button should be bottom right corner of the card right??

**Comment by yazdanhaider** [comment]
> Sure @yazdanhaider so the i button should be bottom right corner of the card right??
> 
> Please kindly confirm I will work on it now

Yes!! Also the popup should close when users click outside the box.

**Comment by Jhananithaa** [comment]
Got it! Will work on it!

**Comment by Jhananithaa** [comment]
@yazdanhaider - i have made a changes. Please kindly review. Hope this meet the requirement!
Thankyou!

https://github.com/user-attachments/assets/9ffcf8f6-15e2-4edb-ab71-607b18bb0a0a

**Comment by yazdanhaider** [comment]
Great @Jhananithaa. Thank you for Contributing!!!

**Pull request merged**
